name: Simple Build Action

on:
  push:
    branches: [ "ghac-test" ]
  pull_request:
    branches: [ "ghac-test" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - id: cache-key
        run: echo "week=$(TZ=Asia/Tokyo date +%W)" >> "$GITHUB_OUTPUT"
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'
  
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        env:
          CACHE_PREFIX_VAR: weekly-cache-${{ steps.cache-key.outputs.week }}
        with:
          cache-read-only: false
          gradle-home-cache-includes: |
            caches
            caches/retro_futura_gradle
            jdks
            wrapper
  
      - name: Build with Gradle Wrapper
        run: ./gradlew build
  
      - uses: actions/upload-artifact@v4
        with:
          name: dev-artifact
          path: |
            build/libs/*.jar
